# Cambiar la tecla líder a "Alt + ,"
# La tecla seguido del 'Alt' es la tecla ','.
unbind C-b          # Desvincular la tecla predeterminada (Ctrl + B)
set-option -g prefix M-,
bind M-, send-prefix

# Configuracion de mouse
setw -g mouse on	

# Mejorar el portapapeles (requiere xclip o wl-clipboard)
set-option -g set-clipboard on

# Barra de estado mejorada
set -g status-bg colour234  # Fondo oscuro
set -g status-fg colour136  # Texto amarillo

# Ir a la siguiente ventana con Leader + j
 bind -n M-n next-window

# Ir a la ventana anterior con Leader + k
 bind -n M-p previous-window

# Cambiar la tecla para abrir una nueva ventana (ejemplo: Leader + m)
 unbind c
 bind -n M-m new-window

# Cambiar la tecla para cerrar una ventana (ejemplo: Leader + d)
 unbind &
 bind -n M-w kill-window

# Renombrar sesión con Leader + R
bind-key r command-prompt "rename-window '%%'"

# Dividir panel en horizontal
bind -n M-g split-window -h

# Dividir panel en vertical
bind -n M-h split-window -v

bind -n M-Left  resize-pane -L 1  # Reducir ancho
bind -n M-Right resize-pane -R 1  # Aumentar ancho
bind -n M-Up    resize-pane -U 1  # Reducir altura
bind -n M-Down  resize-pane -D 1  # Aumentar altura

# Toggle entre paneles sin tecla líder
bind -n M-t select-pane -t :.+
